/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 base-mesh-246-tri.glb --transform 
Files: base-mesh-246-tri.glb [41.84KB] > /Users/Robert.Myers/coding/three-js-examples/public/assets/base-mesh-246-tri-transformed.glb [11.72KB] (72%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber';

const glbPath = '/assets/base-mesh-246-tri-transformed.glb';

/**
 * ```sh
 * npx gltfjsx base-mesh-246-tri.glb  --transform
 * ```
 */
export function BaseMesh246TriModel(props: GroupProps) {
  const imported = useGLTF(glbPath)
  const nodes = imported.nodes as typeof imported.nodes & {
    Cube: {
      geometry: THREE.BufferGeometry;
      material: THREE.Material;
      skeleton: THREE.Skeleton;
    }
  };
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.spine} />
      <skinnedMesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        skeleton={nodes.Cube.skeleton}
        scale={1.333}
      />
    </group>
  )
}

useGLTF.preload(glbPath);
